[workspace]
members = [
    "vibe-ensemble-core",
    "vibe-ensemble-storage",
    "vibe-ensemble-prompts",
    "vibe-ensemble-mcp",
    "vibe-ensemble-web",
    "vibe-ensemble-server",
]
# Using explicit members list for workspace configuration
resolver = "2"

[workspace.package]
version = "0.1.1"
edition = "2021"
authors = ["Vibe Ensemble Team"]
license = "MIT"
repository = "https://github.com/siy/vibe-ensemble-mcp"
description = "MCP server for coordinating multiple Claude Code instances"
rust-version = "1.80"

[workspace.dependencies]
# Async runtime
tokio = { version = "1.0", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Unique identifiers
uuid = { version = "1.0", features = ["v4", "serde"] }

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Logging and observability
tracing = "0.1"
tracing-subscriber = "0.3"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Database
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio-rustls", "sqlite", "postgres", "chrono", "uuid", "macros", "migrate"] }
handlebars = "4.5"

# WebSocket support
tokio-tungstenite = "0.21"
futures-util = "0.3"

# Regex and random utilities
regex = "1.10"
rand = "0.8"
base64 = "0.22"

# Async traits
async-trait = "0.1"
futures = "0.3"

# Web framework for MCP protocol and dashboard  
axum = { version = "0.7", default-features = false, features = ["macros", "json", "tokio", "http1", "query"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace"] }

# Configuration management
config = "0.14"

# Template engine for web dashboard
askama = "0.12"
askama_axum = "0.4"

# HTTP client and utilities
reqwest = "0.12"
hyper = "1.0"
url = "2.5"

# Security and authentication
bcrypt = "0.15"
jsonwebtoken = "9.2"

# Performance optimization dependencies
moka = { version = "0.12", features = ["future"] }  # Async caching
lru = "0.12"                        # LRU cache implementation
dashmap = "5.5"                     # Concurrent HashMap
flate2 = "1.0"                      # Compression
parking_lot = "0.12"                # High-performance synchronization
rayon = "1.8"                       # Data parallelism
num_cpus = "1.16"                   # CPU core detection

# System directories
dirs = "5.0"                        # Platform-appropriate directories