version: '3.8'

# Development override for Docker Compose
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  vibe-ensemble:
    build:
      target: runtime  # Use runtime stage instead of production
    environment:
      - RUST_LOG=debug,vibe_ensemble=trace
      - RUST_BACKTRACE=1
    volumes:
      - .:/app/src:ro  # Mount source for development
    ports:
      - "8080:8080"
      - "9090:9090"    # Expose metrics port
    security_opt: []   # Remove security restrictions for development
    read_only: false  # Allow writes for development

  postgres:
    ports:
      - "5432:5432"    # Expose PostgreSQL port for development tools
    environment:
      - POSTGRES_INITDB_ARGS=--auth-host=trust  # Simplified auth for dev

  redis:
    ports:
      - "6379:6379"    # Expose Redis port for development tools
    command: redis-server --requirepass dev_password  # Simplified config

  nginx:
    ports:
      - "8000:80"      # Use different port to avoid conflicts

  # Development-only services
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: vibe-ensemble-pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@vibe-ensemble.dev
      - PGADMIN_DEFAULT_PASSWORD=dev_password
    ports:
      - "5050:80"
    networks:
      - vibe-network
    depends_on:
      - postgres

  mailhog:
    image: mailhog/mailhog:latest
    container_name: vibe-ensemble-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"   # SMTP port
      - "8025:8025"   # Web UI port
    networks:
      - vibe-network