# Development override for Docker Compose
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  vibe-ensemble:
    build:
      target: runtime  # Use runtime stage instead of production
    environment:
      - RUST_LOG=debug,vibe_ensemble=trace
      - RUST_BACKTRACE=1
      - DATABASE_URL=sqlite:///app/data/vibe-ensemble-dev.db
    volumes:
      - .:/app/src:ro  # Mount source for development
    ports:
      - "8080:8080"
      - "9090:9090"    # Expose metrics port
    security_opt: []   # Remove security restrictions for development
    read_only: false  # Allow writes for development