services:
  vibe-ensemble:
    build:
      context: .
      dockerfile: Dockerfile.optimized
      target: production
    image: vibe-ensemble:latest
    container_name: vibe-ensemble-server
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-8080}:8080"
      - "${METRICS_PORT:-9090}:9090"
    environment:
      - DATABASE_URL=sqlite:///app/data/vibe-ensemble.db
      - RUST_LOG=${RUST_LOG:-info,vibe_ensemble=debug}
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - METRICS_PORT=9090
      - RUST_BACKTRACE=0
    volumes:
      - vibe_data:/app/data
      - vibe_logs:/app/logs
    networks:
      - vibe-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /app/tmp:noexec,nosuid,size=100m


volumes:
  vibe_data:
    driver: local
  vibe_logs:
    driver: local

networks:
  vibe-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24