[server]
host = "127.0.0.1"
port = 8080
workers = 4

[database]
url = "sqlite:./vibe_ensemble.db"
max_connections = 10
migrate_on_startup = true

[mcp]
protocol_version = "1.0.0"
heartbeat_interval = 30
max_message_size = 1048576

[web]
enabled = true
host = "127.0.0.1"
port = 8081

[logging]
level = "info"
format = "json"

[monitoring]
enabled = true
metrics_host = "127.0.0.1"
metrics_port = 9090
health_host = "127.0.0.1"
health_port = 8090
tracing_enabled = true
alerting_enabled = true