# Example configuration for Vibe Ensemble MCP Server
# This file shows available configuration options
# All options have sensible defaults and can be overridden via CLI args

# Database configuration - SQLite only
[database]
# Database file path (default: $HOME/.vibe-ensemble/data.db)
# Note: Tilde (~) expansion is handled by the application
path = "~/.vibe-ensemble/data.db"
# Maximum database connections (default: 10)
max_connections = 10
# Run migrations on startup (default: true)
migrate_on_startup = true

# Web dashboard configuration
[web]
# Web dashboard host (default: 127.0.0.1)
host = "127.0.0.1"
# Web dashboard port (default: 8080)
port = 8080

# Logging configuration
[logging]
# Log level: trace, debug, info, warn, error (default: info)
level = "info"
# Enable debug logging for specific modules
debug_modules = ["vibe_ensemble_mcp", "vibe_ensemble_web"]