apiVersion: v1
kind: ConfigMap
metadata:
  name: vibe-ensemble-config-staging
  namespace: vibe-ensemble-staging
  labels:
    app.kubernetes.io/name: vibe-ensemble
    app.kubernetes.io/component: config
    app.kubernetes.io/environment: staging
data:
  config.toml: |
    [server]
    host = "0.0.0.0"
    port = 8080
    max_connections = 1000
    request_timeout_seconds = 30
    shutdown_timeout_seconds = 30
    worker_threads = 4
    max_blocking_threads = 128

    [database]
    max_connections = 20
    connection_timeout_seconds = 5
    idle_timeout_seconds = 300
    min_connections = 5
    max_lifetime_seconds = 1800
    test_before_acquire = true

    [mcp]
    transport = "websocket"
    timeout_seconds = 30
    max_message_size = 1048576  # 1MB
    heartbeat_interval_seconds = 30
    max_concurrent_connections = 100

    [security]
    jwt_expiry_hours = 8
    password_min_length = 8
    rate_limit_requests_per_hour = 1000
    cors_max_age_seconds = 3600
    require_https = false  # Allow HTTP for staging
    secure_cookies = false

    [logging]
    level = "debug"
    format = "json"
    target = "stdout"
    include_location = true

    [metrics]
    enabled = true
    port = 9090
    path = "/metrics"
    collect_interval_seconds = 15

    [features]
    api_docs = true  # Enable API docs in staging
    debug_endpoints = true  # Enable debug endpoints
    health_endpoint = true
    websocket_enabled = true
    monitoring_enabled = true
    authentication_required = false  # Relaxed for testing

    [cache]
    enabled = true
    default_ttl_seconds = 60
    max_size = 1000

    [performance]
    enable_request_compression = true
    compression_level = 3
    max_request_size_mb = 10

    [monitoring]
    health_check_interval_seconds = 15
    metrics_collection_interval_seconds = 15
    trace_sampling_rate = 1.0  # Full tracing in staging
    enable_distributed_tracing = true

  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        environment: 'staging'
        cluster: 'staging'

    scrape_configs:
      - job_name: 'vibe-ensemble-staging'
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - vibe-ensemble-staging
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          action: keep
          regex: vibe-ensemble-service
        metrics_path: /metrics
        scrape_interval: 15s

  grafana-datasources.yml: |
    apiVersion: 1
    datasources:
    - name: Prometheus-Staging
      type: prometheus
      access: proxy
      url: http://prometheus-staging:9090
      isDefault: true
      editable: true