apiVersion: v1
kind: Namespace
metadata:
  name: vibe-ensemble
  labels:
    name: vibe-ensemble
    app.kubernetes.io/name: vibe-ensemble
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: vibe-ensemble-mcp
---
apiVersion: v1
kind: LimitRange
metadata:
  name: vibe-ensemble-limits
  namespace: vibe-ensemble
spec:
  limits:
  - default:
      cpu: "1000m"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: vibe-ensemble-quota
  namespace: vibe-ensemble
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"