apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vibe-ensemble-pdb
  namespace: vibe-ensemble
  labels:
    app.kubernetes.io/name: vibe-ensemble
    app.kubernetes.io/component: reliability
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: vibe-ensemble
      app.kubernetes.io/component: server

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres-pdb
  namespace: vibe-ensemble
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database-reliability
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres