name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    - uses: Swatinem/rust-cache@v2
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
      env:
        SQLX_OFFLINE: true
    - name: Run tests
      run: cargo test
      env:
        SQLX_OFFLINE: true
    - name: Check build
      run: cargo check --release
      env:
        SQLX_OFFLINE: true