name: Integration Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run integration tests nightly at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: sqlite:./integration_test.db
  RUSTFLAGS: "-D warnings"
  SQLX_OFFLINE: true

concurrency:
  group: integration-tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coordinator-ticket-management:
    name: Coordinator Ticket Management
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "stable"

      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-coordinator-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-coordinator-
            ${{ runner.os }}-

      - name: Test coordinator ticket management functionality
        run: |
          # Test coordinator creating and assigning tickets to specialized workers
          cargo test --test coordinator_worker_integration test_coordinator_creates_assigns_tickets --verbose -- --nocapture
        env:
          RUST_BACKTRACE: 1
          DATABASE_URL: sqlite:./coordinator_test.db

  workspace-isolation:
    name: Multi-Worker Workspace Isolation
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "stable"

      - name: Set up git for workspace tests
        run: |
          git config --global user.name "Workspace Tests"
          git config --global user.email "workspace-tests@vibe-ensemble.local"
          git config --global init.defaultBranch main

      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-workspace-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-workspace-
            ${{ runner.os }}-

      - name: Test workspace isolation between multiple workers
        run: |
          # Test multiple workers working on same project in isolated workspaces
          cargo test --test coordinator_worker_integration test_multi_worker_isolated_workspaces --verbose -- --nocapture
        env:
          RUST_BACKTRACE: 1
          DATABASE_URL: sqlite:./workspace_test.db

  error-recovery:
    name: Error Recovery and Task Reassignment
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "stable"

      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-recovery-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-recovery-
            ${{ runner.os }}-

      - name: Test error recovery and task reassignment workflows
        run: |
          # Test failure scenarios, task reassignment, and recovery procedures
          cargo test --test coordinator_worker_integration test_error_recovery_workflow --verbose -- --nocapture
        env:
          RUST_BACKTRACE: 1
          DATABASE_URL: sqlite:./recovery_test.db

  complete-integration-suite:
    name: Complete Integration Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "stable"
          components: rustfmt, clippy

      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-complete-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-complete-
            ${{ runner.os }}-

      - name: Build integration tests
        run: |
          cargo build --workspace --tests

      - name: Run all integration tests together
        run: |
          # Run all three integration tests to ensure they work together
          cargo test --test coordinator_worker_integration --verbose -- --nocapture
        env:
          RUST_BACKTRACE: 1
          DATABASE_URL: sqlite:./complete_integration_test.db

      - name: Lint integration tests
        run: |
          # Ensure integration tests follow coding standards
          cargo clippy --tests --package vibe-ensemble-mcp -- -D warnings